
import { Difficulty, Exercise } from './types';

export const EXERCISES: Exercise[] = [
  // --- KĀJAS UN SĒŽA ---
  { id: 'sq-1', name: 'Klasiskie pietupieni', description: 'Kāju pamatvingrinājums.', baseCalories: 0.5, difficulty: [Difficulty.EASY, Difficulty.MEDIUM] },
  { id: 'sq-2', name: 'Sumo pietupieni', description: 'Plats stāvs, pēdas izvērstas.', baseCalories: 0.6, difficulty: [Difficulty.EASY, Difficulty.MEDIUM, Difficulty.HARD] },
  { id: 'sq-3', name: 'Pietupienu pulss', description: 'Mazs, atsperīgs kustību diapazons lejasdaļā.', baseCalories: 0.7, difficulty: [Difficulty.MEDIUM, Difficulty.HARD] },
  { id: 'sq-4', name: 'Pietupiens ar palēcienu', description: 'Eksplozīvs lēciens uz augšu no pietupiena.', baseCalories: 1.5, difficulty: [Difficulty.HARD] },
  { id: 'sq-5', name: 'Šaurie pietupieni', description: 'Kājas kopā, svars uz papēžiem.', baseCalories: 0.5, difficulty: [Difficulty.EASY, Difficulty.MEDIUM] },
  { id: 'sq-6', name: 'Sānu izklupieni', description: 'Solis uz sāniem, iesēžoties vienā kājā.', baseCalories: 0.8, difficulty: [Difficulty.MEDIUM, Difficulty.HARD] },
  { id: 'sq-7', name: 'Izklupieni uz priekšu', description: 'Solis uz priekšu, abi ceļi 90 grādos.', baseCalories: 0.7, difficulty: [Difficulty.EASY, Difficulty.MEDIUM] },
  { id: 'sq-8', name: 'Izklupieni atpakaļ', description: 'Solis atpakaļ, saudzīgāks ceļiem.', baseCalories: 0.7, difficulty: [Difficulty.EASY, Difficulty.MEDIUM] },
  { id: 'sq-9', name: 'Bulgāru izklupieni (viena kāja)', description: 'Viena kāja pacelta uz gultas vai krēsla.', baseCalories: 1.2, difficulty: [Difficulty.HARD] },
  { id: 'sq-10', name: 'Lēcieni izklupienā', description: 'Maini kājas lēcienā.', baseCalories: 2.0, difficulty: [Difficulty.HARD] },
  { id: 'sq-11', name: 'Dāmu (Curtsy) izklupieni', description: 'Solis pa diagonāli atpakaļ.', baseCalories: 0.8, difficulty: [Difficulty.MEDIUM, Difficulty.HARD] },
  { id: 'sq-12', name: 'Sēdēšana pie sienas', description: 'Statiskais turējums pie sienas (sekundes).', baseCalories: 0.4, difficulty: [Difficulty.EASY, Difficulty.MEDIUM, Difficulty.HARD] },
  { id: 'sq-13', name: 'Kāju celšana sānis stāvus', description: 'Līdzsvars un gūžu muskulatūra.', baseCalories: 0.4, difficulty: [Difficulty.EASY] },
  { id: 'sq-14', name: 'Kāpšana uz krēsla', description: 'Līp uz paaugstinājuma.', baseCalories: 1.0, difficulty: [Difficulty.MEDIUM, Difficulty.HARD] },
  { id: 'sq-15', name: 'Gurnu pacelšana (Guļus)', description: 'Sēžas muskulatūras stiprināšana.', baseCalories: 0.4, difficulty: [Difficulty.EASY, Difficulty.MEDIUM] },
  { id: 'sq-16', name: 'Gurnu pacelšana uz vienas kājas', description: 'Lielāka slodze vienai pusei.', baseCalories: 0.8, difficulty: [Difficulty.MEDIUM, Difficulty.HARD] },
  { id: 'sq-17', name: 'Vardes lēcieni', description: 'Plats lēciens uz priekšu no pietupiena.', baseCalories: 1.8, difficulty: [Difficulty.HARD] },
  { id: 'sq-18', name: 'Skeiteri (Skaters)', description: 'Sānu lēcieni kā slidojot.', baseCalories: 1.4, difficulty: [Difficulty.MEDIUM, Difficulty.HARD] },
  { id: 'sq-19', name: 'Pietupiens ar pieskārienu zemei', description: 'Dinamisks pietupiens.', baseCalories: 0.9, difficulty: [Difficulty.MEDIUM] },
  { id: 'sq-20', name: 'Gurnu apļi stāvus', description: 'Mobilitātes uzlabošanai.', baseCalories: 0.2, difficulty: [Difficulty.EASY] },

  // --- AUGŠĶERMENIS ---
  { id: 'ub-1', name: 'Atspiedieni uz ceļiem', description: 'Atvieglota atspiedienu versija.', baseCalories: 0.8, difficulty: [Difficulty.EASY] },
  { id: 'ub-2', name: 'Klasiskie atspiedieni', description: 'Krūšu un roku spēks.', baseCalories: 1.2, difficulty: [Difficulty.MEDIUM, Difficulty.HARD] },
  { id: 'ub-3', name: 'Platie atspiedieni', description: 'Lielāks uzsvars uz krūšu muskuļiem.', baseCalories: 1.3, difficulty: [Difficulty.MEDIUM, Difficulty.HARD] },
  { id: 'ub-4', name: 'Dimanta atspiedieni', description: 'Plaukstas kopā zem krūtīm (tricepsam).', baseCalories: 1.5, difficulty: [Difficulty.HARD] },
  { id: 'ub-5', name: 'Pike Pushups', description: 'Gurni gaisā, galva uz leju (pleciem).', baseCalories: 1.4, difficulty: [Difficulty.HARD] },
  { id: 'ub-6', name: 'Tricepsa izspiedieni no krēsla', description: 'Roku aizmugurējās daļas treniņš.', baseCalories: 1.0, difficulty: [Difficulty.MEDIUM, Difficulty.HARD] },
  { id: 'ub-7', name: 'Roku apļi (sekundes)', description: 'Turi rokas izstieptas un veic mazus apļus.', baseCalories: 0.3, difficulty: [Difficulty.EASY, Difficulty.MEDIUM] },
  { id: 'ub-8', name: 'Plank-to-Pushup', description: 'Pāreja no elkoņiem uz plaukstām.', baseCalories: 1.6, difficulty: [Difficulty.MEDIUM, Difficulty.HARD] },
  { id: 'ub-9', name: 'Supermens (Hold)', description: 'Muguras muskulatūra.', baseCalories: 0.4, difficulty: [Difficulty.EASY, Difficulty.MEDIUM] },
  { id: 'ub-10', name: 'Sānu planks ar paceltu roku', description: 'Stabilitāte un sānu muskuļi.', baseCalories: 0.6, difficulty: [Difficulty.MEDIUM] },
  { id: 'ub-11', name: 'Roku boksēšana gaisā', description: 'Ātri sitieni uz priekšu.', baseCalories: 0.9, difficulty: [Difficulty.EASY, Difficulty.MEDIUM] },
  { id: 'ub-12', name: 'Peldēšana sausumā', description: 'Guļot uz vēdera, imitē peldēšanu.', baseCalories: 0.6, difficulty: [Difficulty.MEDIUM] },
  { id: 'ub-13', name: 'Lāča gaita atpakaļgaitā', description: 'Koordinācija un spēks.', baseCalories: 1.7, difficulty: [Difficulty.HARD] },
  { id: 'ub-14', name: 'Atspiedieni pret sienu', description: 'Visvieglākā versija.', baseCalories: 0.4, difficulty: [Difficulty.EASY] },
  { id: 'ub-15', name: 'Plecu pieskārieni plankā', description: 'Pieskaries pretējam plecam plaukstu plankā.', baseCalories: 1.1, difficulty: [Difficulty.MEDIUM, Difficulty.HARD] },
  { id: 'ub-16', name: 'Zirneklis (Spider pushups)', description: 'Celiet celi pie elkoņa atspiediena laikā.', baseCalories: 2.0, difficulty: [Difficulty.HARD] },
  { id: 'ub-17', name: 'Roku šūpoles virs galvas', description: 'Mobilitāte.', baseCalories: 0.3, difficulty: [Difficulty.EASY] },
  { id: 'ub-18', name: 'Plaukstu savilkšana aiz muguras', description: 'Stājas uzlabošanai.', baseCalories: 0.2, difficulty: [Difficulty.EASY] },
  { id: 'ub-19', name: 'Atspiediens ar rokas pacelšanu', description: 'Pēc atspiediena izstiep roku uz priekšu.', baseCalories: 1.4, difficulty: [Difficulty.HARD] },
  { id: 'ub-20', name: 'Tricepsa atspiediens pret grīdu', description: 'Šauri elkoņi pie sāniem.', baseCalories: 1.3, difficulty: [Difficulty.MEDIUM] },

  // --- KORSETE UN VĒDERS ---
  { id: 'ab-1', name: 'Klasiskā presīte (Crunches)', description: 'Cel tikai plecus no zemes.', baseCalories: 0.5, difficulty: [Difficulty.EASY, Difficulty.MEDIUM] },
  { id: 'ab-2', name: 'Pilnā presīte (Sit-ups)', description: 'Celies līdz sēdus pozīcijai.', baseCalories: 0.8, difficulty: [Difficulty.MEDIUM, Difficulty.HARD] },
  { id: 'ab-3', name: 'Bicycle Crunches', description: 'Pretējais elkonis pie pretējā ceļa.', baseCalories: 1.2, difficulty: [Difficulty.MEDIUM, Difficulty.HARD] },
  { id: 'ab-4', name: 'Kāju celšana guļus', description: 'Vēdera lejasdaļai.', baseCalories: 0.9, difficulty: [Difficulty.MEDIUM, Difficulty.HARD] },
  { id: 'ab-5', name: 'Krievu tvists (Russian Twist)', description: 'Sēdus rotācija no vienas puses uz otru.', baseCalories: 1.0, difficulty: [Difficulty.MEDIUM, Difficulty.HARD] },
  { id: 'ab-6', name: 'Elkoņu planks (sekundes)', description: 'Stabils turējums.', baseCalories: 0.4, difficulty: [Difficulty.EASY, Difficulty.MEDIUM, Difficulty.HARD] },
  { id: 'ab-7', name: 'Plaukstu planks (sekundes)', description: 'Turējums uz taisnām rokām.', baseCalories: 0.4, difficulty: [Difficulty.EASY, Difficulty.MEDIUM] },
  { id: 'ab-8', name: 'Sānu planks (sekundes)', description: 'Balsts uz viena elkoņa.', baseCalories: 0.5, difficulty: [Difficulty.MEDIUM, Difficulty.HARD] },
  { id: 'ab-9', name: 'Kalnā kāpēji (Mountain Climbers)', description: 'Ātra ceļu pievilkšana pie krūtīm.', baseCalories: 1.5, difficulty: [Difficulty.MEDIUM, Difficulty.HARD] },
  { id: 'ab-10', name: 'Flutter Kicks', description: 'Mazi, ātri kāju vēzieni guļus.', baseCalories: 0.8, difficulty: [Difficulty.MEDIUM, Difficulty.HARD] },
  { id: 'ab-11', name: 'Scissors (Šķēres)', description: 'Krusto kājas guļus pozīcijā.', baseCalories: 0.8, difficulty: [Difficulty.MEDIUM, Difficulty.HARD] },
  { id: 'ab-12', name: 'Dead Bug', description: 'Lēna, kontrolēta roku un kāju kustība.', baseCalories: 0.4, difficulty: [Difficulty.EASY, Difficulty.MEDIUM] },
  { id: 'ab-13', name: 'V-Up', description: 'Vienlaicīgi cel rokas un kājas, veidojot V.', baseCalories: 1.5, difficulty: [Difficulty.HARD] },
  { id: 'ab-14', name: 'Hollow Body Hold', description: 'Statiskais turējums (laiviņa).', baseCalories: 0.7, difficulty: [Difficulty.HARD] },
  { id: 'ab-15', name: 'Plank Jacks', description: 'Kājas platāk/kopā lēcienā planka pozīcijā.', baseCalories: 1.4, difficulty: [Difficulty.MEDIUM, Difficulty.HARD] },
  { id: 'ab-16', name: 'Gurnu noliekšana plankā', description: 'Grozies elkoņu plankā uz sāniem.', baseCalories: 1.1, difficulty: [Difficulty.MEDIUM, Difficulty.HARD] },
  { id: 'ab-17', name: 'Ceļu pievilkšana sēdus', description: 'Roku balsts aiz muguras, pievelc ceļus.', baseCalories: 0.9, difficulty: [Difficulty.MEDIUM] },
  { id: 'ab-18', name: 'Pieskāriens pie papēžiem', description: 'Guļot uz muguras, sniedzies pie papēžiem.', baseCalories: 0.5, difficulty: [Difficulty.EASY, Difficulty.MEDIUM] },
  { id: 'ab-19', name: 'Putns-Suns (Bird Dog)', description: 'Pretējā roka un kāja izstiepta plankā.', baseCalories: 0.4, difficulty: [Difficulty.EASY, Difficulty.MEDIUM] },
  { id: 'ab-20', name: 'Reversā presīte', description: 'Cel gurnus uz augšu no muguras.', baseCalories: 0.8, difficulty: [Difficulty.MEDIUM] },

  // --- KARDIO UN KOMBINĀCIJAS ---
  { id: 'cd-1', name: 'Jumping Jacks', description: 'Klasisks lēciens ar rokām/kājām.', baseCalories: 1.0, difficulty: [Difficulty.EASY, Difficulty.MEDIUM, Difficulty.HARD] },
  { id: 'cd-2', name: 'Augstie ceļi (High Knees)', description: 'Skriešana vietā, ceļi augstu.', baseCalories: 1.2, difficulty: [Difficulty.MEDIUM, Difficulty.HARD] },
  { id: 'cd-3', name: 'Papēži pie sēžas', description: 'Ātra kāju mainīšana.', baseCalories: 0.9, difficulty: [Difficulty.EASY, Difficulty.MEDIUM] },
  { id: 'cd-4', name: 'Burpees (Bez atspiediena)', description: 'Iesēdiens, kājas atpakaļ, lēciens.', baseCalories: 1.8, difficulty: [Difficulty.MEDIUM, Difficulty.HARD] },
  { id: 'cd-5', name: 'Pilnie Burpees', description: 'Burpee ar atspiedienu.', baseCalories: 2.5, difficulty: [Difficulty.HARD] },
  { id: 'cd-6', name: 'Kāpurķēde (Inchworm)', description: 'Ej ar rokām uz priekšu un atpakaļ.', baseCalories: 1.2, difficulty: [Difficulty.MEDIUM] },
  { id: 'cd-7', name: 'Zvaigznes lēcieni (Star Jumps)', description: 'Gaisā kā zvaigzne.', baseCalories: 2.2, difficulty: [Difficulty.HARD] },
  { id: 'cd-8', name: 'Shadow Boxing', description: 'Boksēšana vietā ar kāju kustībām.', baseCalories: 1.1, difficulty: [Difficulty.EASY, Difficulty.MEDIUM, Difficulty.HARD] },
  { id: 'cd-9', name: 'Izkāpieni vietā', description: 'Simulē ātru iešanu pa kāpnēm.', baseCalories: 0.8, difficulty: [Difficulty.EASY] },
  { id: 'cd-10', name: 'Spēka palēcieni (Power Jacks)', description: 'Zems pietupiens + lēciens.', baseCalories: 1.6, difficulty: [Difficulty.MEDIUM, Difficulty.HARD] },
  { id: 'cd-11', name: 'Seal Jacks', description: 'Lēcieni, rokas plaukšķinot priekšā.', baseCalories: 1.0, difficulty: [Difficulty.EASY, Difficulty.MEDIUM] },
  { id: 'cd-12', name: 'Lāča gaita (Bear Crawl)', description: 'Rāpošana uz četrām, ceļi virs zemes.', baseCalories: 1.8, difficulty: [Difficulty.MEDIUM, Difficulty.HARD] },
  { id: 'cd-13', name: 'Krabja gaita', description: 'Pārvietošanās sēdus pozīcijā ar rokām.', baseCalories: 1.4, difficulty: [Difficulty.MEDIUM] },
  { id: 'cd-14', name: 'Lēcieni no sāna uz sānu', description: 'Kā pāri neredzamai līnijai.', baseCalories: 1.1, difficulty: [Difficulty.MEDIUM] },
  { id: 'cd-15', name: 'Pievilkšanās vietā (Simulācija)', description: 'Roku vēzieni lejup ar pretestību.', baseCalories: 0.4, difficulty: [Difficulty.EASY] },
  { id: 'cd-16', name: 'Skriešana vietā (sekundes)', description: 'Viegls skrējiens.', baseCalories: 0.7, difficulty: [Difficulty.EASY, Difficulty.MEDIUM] },
  { id: 'cd-17', name: 'Tuck Jumps', description: 'Lēciens, ceļus pievelkot pie krūtīm.', baseCalories: 2.6, difficulty: [Difficulty.HARD] },
  { id: 'cd-18', name: 'Pus-Burpee', description: 'Tikai lejasdaļas kustība.', baseCalories: 1.5, difficulty: [Difficulty.MEDIUM] },
  { id: 'cd-19', name: 'Rotācijas lēcieni', description: 'Lēciens ar 180 grādu pagriezienu.', baseCalories: 2.0, difficulty: [Difficulty.HARD] },
  { id: 'cd-20', name: 'Boksa soļi', description: 'Ritmiska lēkāšana no kājas uz kāju.', baseCalories: 0.8, difficulty: [Difficulty.EASY, Difficulty.MEDIUM] },

  // --- MOBILITĀTE UN PAPILDUS ---
  { id: 'mo-1', name: 'Kaķis-Govs', description: 'Muguras izliekšana četrrāpus.', baseCalories: 0.2, difficulty: [Difficulty.EASY] },
  { id: 'mo-2', name: 'Zemup vērsts suns (sekundes)', description: 'Jogas poza stiepšanai.', baseCalories: 0.3, difficulty: [Difficulty.EASY, Difficulty.MEDIUM] },
  { id: 'mo-3', name: 'Kobra (Hold)', description: 'Vēdera priekšas stiepšana.', baseCalories: 0.2, difficulty: [Difficulty.EASY] },
  { id: 'mo-4', name: 'Plecu apļi', description: 'Lēni un plaši.', baseCalories: 0.1, difficulty: [Difficulty.EASY] },
  { id: 'mo-5', name: 'Dziļais pietupiens (Hold)', description: 'Gurnu atvēršana.', baseCalories: 0.4, difficulty: [Difficulty.MEDIUM] },
  { id: 'mo-6', name: 'Kāju šūpošana uz priekšu', description: 'Līdzsvars un dinamika.', baseCalories: 0.4, difficulty: [Difficulty.EASY] },
  { id: 'mo-7', name: 'Taisnas muguras noliekšanās', description: 'Stiepj augšstilbu aizmuguri.', baseCalories: 0.3, difficulty: [Difficulty.EASY] },
  { id: 'mo-8', name: 'Pēdu rotācija', description: 'Siltuma sajūtai.', baseCalories: 0.1, difficulty: [Difficulty.EASY] },
  { id: 'mo-9', name: 'Torakālā rotācija (četrrāpus)', description: 'Krūšu daļas atvēršana.', baseCalories: 0.3, difficulty: [Difficulty.EASY, Difficulty.MEDIUM] },
  { id: 'mo-10', name: 'Bērna poza (sekundes)', description: 'Atslodze mugurai.', baseCalories: 0.1, difficulty: [Difficulty.EASY] },

  // --- VAIRĀK VARIĀCIJU LĪDZ 100+ ---
  { id: 'v-1', name: 'Pietupiens ar celi pie elkoņa', description: 'Kombinēts pietupiens ar presīti.', baseCalories: 1.1, difficulty: [Difficulty.MEDIUM, Difficulty.HARD] },
  { id: 'v-2', name: 'Izklupiens ar rokas stiepšanu', description: 'Gara līnija no pēdas līdz plaukstai.', baseCalories: 0.9, difficulty: [Difficulty.MEDIUM] },
  { id: 'v-3', name: 'Dimanta presīte', description: 'Kājas saliektas "tauriņā", sēdus.', baseCalories: 0.9, difficulty: [Difficulty.MEDIUM] },
  { id: 'v-4', name: 'Komando Planks', description: 'Nolaidies uz elkoņiem un celies augšā.', baseCalories: 1.6, difficulty: [Difficulty.HARD] },
  { id: 'v-5', name: 'Pistoļu pietupieni (atvieglotie)', description: 'Pietupiens uz vienas kājas, turoties pie sienas.', baseCalories: 1.5, difficulty: [Difficulty.HARD] },
  { id: 'v-6', name: 'T-veida līdzsvars', description: 'Stāvi uz vienas kājas, ķermenis kā T.', baseCalories: 0.5, difficulty: [Difficulty.MEDIUM] },
  { id: 'v-7', name: 'Planks ar kājas celšanu', description: 'Turiet taisnu līniju.', baseCalories: 1.2, difficulty: [Difficulty.MEDIUM, Difficulty.HARD] },
  { id: 'v-8', name: 'Vēdera presīte "Varde"', description: 'Kājas gaisā, pēdas kopā.', baseCalories: 1.1, difficulty: [Difficulty.MEDIUM] },
  { id: 'v-9', name: 'Atspiedieni ar clap', description: 'Lēciens ar rokām gaisā.', baseCalories: 3.0, difficulty: [Difficulty.HARD] },
  { id: 'v-10', name: 'Atspiedieni piramīdā', description: 'Sāc ar 1, tad 2, tad 3 (kopā skaits).', baseCalories: 1.5, difficulty: [Difficulty.HARD] },
  { id: 'v-11', name: 'Sānu izklupiens ar palēcienu', description: 'Dinamiska kombinācija.', baseCalories: 1.9, difficulty: [Difficulty.HARD] },
  { id: 'v-12', name: 'Kāju rotācija guļus', description: 'Zīmē apļus gaisā.', baseCalories: 1.0, difficulty: [Difficulty.HARD] },
  { id: 'v-13', name: 'Gurnu tiltiņš uz papēžiem', description: 'Lielāks uzsvars uz ikriem.', baseCalories: 0.6, difficulty: [Difficulty.MEDIUM] },
  { id: 'v-14', name: 'Izklupiens uz sāniem ar rotāciju', description: 'Grozies pret strādājošo kāju.', baseCalories: 1.1, difficulty: [Difficulty.MEDIUM] },
  { id: 'v-15', name: 'Boksa "āķi" gaisā', description: 'Sānu sitieni.', baseCalories: 1.0, difficulty: [Difficulty.MEDIUM] },
  { id: 'v-16', name: 'Boksa "augšpēdi" (Uppercuts)', description: 'Sitieni no apakšas uz augšu.', baseCalories: 1.0, difficulty: [Difficulty.MEDIUM] },
  { id: 'v-17', name: 'Planks ar gurnu pacelšanu', description: 'No planka uz "kalnu" un atpakaļ.', baseCalories: 1.3, difficulty: [Difficulty.MEDIUM] },
  { id: 'v-18', name: 'Atspiedieni ar ceļgala pieskārienu', description: 'Atspiediens + celi pie elkoņa.', baseCalories: 1.8, difficulty: [Difficulty.HARD] },
  { id: 'v-19', name: 'Klusais lēciens', description: 'Lec pēc iespējas mīkstāk un klusāk.', baseCalories: 1.2, difficulty: [Difficulty.MEDIUM] },
  { id: 'v-20', name: 'Lēna gaita vietā (High Knees Slow)', description: 'Kontrolēta balansēšana.', baseCalories: 0.5, difficulty: [Difficulty.EASY] },
  { id: 'v-21', name: 'Roku apļi uz aizmuguri', description: 'Atver krūšu kurvi.', baseCalories: 0.3, difficulty: [Difficulty.EASY] }
];

export const DIFFICULTY_CONFIG = {
  [Difficulty.EASY]: {
    repRange: [10, 20],
    color: 'bg-green-500',
    hoverColor: 'hover:bg-green-600',
    textColor: 'text-green-700'
  },
  [Difficulty.MEDIUM]: {
    repRange: [20, 40],
    color: 'bg-orange-500',
    hoverColor: 'hover:bg-orange-600',
    textColor: 'text-orange-700'
  },
  [Difficulty.HARD]: {
    repRange: [40, 80],
    color: 'bg-red-600',
    hoverColor: 'hover:bg-red-700',
    textColor: 'text-red-700'
  }
};
